server:
  port: 9000
  ssl:
    enabled: false

spring:
  application:
    name: auth-server

logging:
  level:
    org.springframework.security: DEBUG
    io.spring.demo: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    health:
      show-details: always
