server:
  port: 8080

spring:
  application:
    name: resource-server
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-server:9000/oauth2/jwks
          issuer-uri: http://auth-server:9000

opa:
  url: http://opa:8181

logging:
  level:
    org.springframework.security: INFO
    io.spring.demo: DEBUG
    AUDIT: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    health:
      show-details: always
